name: Build and Deploy to AKS

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image
      run: az acr login --name unicxacr

    - run: |
        IMAGE_NAME=unicxacr.azurecr.io/unicx-integration
        TAG_ID=${{ github.run_id }}
        docker build -t $IMAGE_NAME:$TAG_ID -t $IMAGE_NAME:latest .
        docker push $IMAGE_NAME:$TAG_ID
        docker push $IMAGE_NAME:latest

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS credentials
      run: az aks get-credentials --resource-group unicx-dev --name unicxdev-aks-kubernetes --overwrite-existing
    
    - name: Create or update Kubernetes Secret
      run: |
          kubectl create secret generic app-secrets \
            --from-literal=MONGODB_URI="${{ secrets.MONGODB_URI }}" \
            --from-literal=JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --from-literal=EMAIL_USER="${{ secrets.EMAIL_USER }}" \
            --from-literal=EMAIL_PASS="${{ secrets.EMAIL_PASS }}" \
            --from-literal=ENCRYPTION_KEY="${{ secrets.ENCRYPTION_KEY }}" \
            --from-literal=AZURE_STORAGE_CONNECTION_STRING="${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
            --from-literal=AZURE_SERVICE_BUS_CONNECTION_STRING="${{ secrets.AZURE_SERVICE_BUS_CONNECTION_STRING }}" \
            --from-literal=CLEAN_DATABASE="${{ secrets.CLEAN_DATABASE }}" \
            --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy with Helm
      run: |
        helm upgrade --install unicx ./deployment/integration-chart --namespace nginx-ingress